name: Extract y Load con Python Bici

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'  # Ejecutar cada minuto

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'  # caching pip dependencies

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ejecutar script de extracción
        run: python project_final_extract.py

      - name: Subir datos de endpoint_1
        uses: actions/upload-artifact@v2
        with:
          name: bici_data_endpoint_1
          path: endpoint_1.csv

      - name: Subir datos de endpoint_2
        uses: actions/upload-artifact@v2
        with:
          name: bici_data_endpoint_2
          path: endpoint_2.csv

  load:
    runs-on: ubuntu-latest
    needs: extract
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'  # caching pip dependencies

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Descargar datos de Extract
        uses: actions/download-artifact@v2
        with:
          name: bici_data_endpoint_1

      - name: Descargar datos de Extract
        uses: actions/download-artifact@v2
        with:
          name: bici_data_endpoint_2

      - name: Subir datos a Snowflake
        run: python project_final_load.py
        env:
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}

